Repository gfoidl/trx2junit, pull requests merged in 2018-09, with the labels that each got.

#13 Add support for `Warning` result summaries
  source/trx2junit/Models/Outcome.cs
  tests/trx2junit.Tests/Internal/TrxParserTests/Parse.cs
  tests/trx2junit.Tests/data/mstest-warning.trx
Labels: MsTest, enhancement

#17 Tests for multiple-args and globbing-args (via shell expansion)
  .circleci/config.yml
  source/trx2junit/InternalsVisibleTo.cs
  source/trx2junit/Program.cs
  source/trx2junit/Worker.cs
  tests/trx2junit.Tests/WorkerTests/Convert.cs
  tests/trx2junit.Tests/WorkerTests/RunAsync.cs
  trx2junit.sln
  verify-xml.sh
Labels: continuous-integration

#19 Unit-tests validate against junit.xsd
  tests/trx2junit.Tests/ValidationHelper.cs
  tests/trx2junit.Tests/WorkerTests/Convert.cs
  tests/trx2junit.Tests/trx2junit.Tests.csproj
Labels: continuous-integration

#21 Diffferent output-location can be specified
  .circleci/config.yml
  ReadMe.md
  source/trx2junit/Program.cs
  source/trx2junit/Resources/Strings.Designer.cs
  source/trx2junit/Resources/Strings.resx
  source/trx2junit/Worker.cs
  source/trx2junit/WorkerOptions.cs
  source/trx2junit/trx2junit.csproj
  tests/trx2junit.Tests/WorkerOptionsTests/Parse.cs
  tests/trx2junit.Tests/WorkerTests/GetJunitFile.cs
  tests/trx2junit.Tests/WorkerTests/RunAsync/DifferentOutputLocation.cs
  tests/trx2junit.Tests/WorkerTests/RunAsync/SameOutputLocation.cs
Labels: enhancement
