Repository gfoidl/trx2junit, pull requests merged in 2019-04, with the labels that each got.

#38 TestDefinitions with 1:n UnitTestResults
  .gitignore
  source/trx2junit/Internal/JUnitBuilder.cs
  source/trx2junit/Internal/TrxParser.cs
  source/trx2junit/Models/Test.cs
  tests/trx2junit.Tests/Internal/JUnitBuilderTests/Build/Base.cs
  tests/trx2junit.Tests/Internal/JUnitBuilderTests/Build/DataDriven.cs
  tests/trx2junit.Tests/Internal/JUnitBuilderTests/Build/Default.cs
Labels: MsTest, enhancement

#41 Code Coverage and CI updates
  .circleci/config.yml
  ReadMe.md
  build.sh
Labels: continuous-integration

#42 Improved CI in the case of Unit-test failures
  .circleci/config.yml
  build.sh
Labels: continuous-integration

#40 More tests for data driven trx-Files
  samples/MsTestSample/DataDriven.cs
  samples/NUnitSample/DataDriven.cs
  samples/NUnitSample/MemberData.cs
  samples/XUnitSample/DataDriven.cs
  samples/XUnitSample/MemberData.cs
  source/trx2junit/Internal/JUnitBuilder.cs
  source/trx2junit/Internal/TrxParser.cs
  tests/trx2junit.Tests/Internal/JUnitBuilderTests/Integration.cs
  tests/trx2junit.Tests/Internal/TrxParserTests/Parse.cs
  tests/trx2junit.Tests/WorkerTests/Convert.cs
  tests/trx2junit.Tests/data/mstest-datadriven-no-failures.trx
  tests/trx2junit.Tests/data/mstest-datadriven.trx
  tests/trx2junit.Tests/data/nunit-datadriven.trx
  tests/trx2junit.Tests/data/nunit-memberdata.trx
  tests/trx2junit.Tests/data/xunit-datadriven.trx
  tests/trx2junit.Tests/data/xunit-memberdata.trx
  tests/trx2junit.Tests/data/xunit.trx
Labels: MsTest, NUnit, continuous-integration, xunit

#46 Handle ignored tests
  samples/MsTestSample/SimpleTests.cs
  samples/NUnitSample/SimpleTests.cs
  samples/XUnitSample/SimpleTests.cs
  schemas/junit.xsd
  source/trx2junit/Internal/JUnitBuilder.cs
  source/trx2junit/Internal/TrxParser.cs
  tests/trx2junit.Tests/DummyTests.cs
  tests/trx2junit.Tests/Internal/JUnitBuilderTests/Integration.cs
  tests/trx2junit.Tests/Internal/TrxParserTests/Parse.cs
  tests/trx2junit.Tests/WorkerTests/Convert.cs
  tests/trx2junit.Tests/data/mstest-ignore.trx
  tests/trx2junit.Tests/data/nunit-ignore.trx
  tests/trx2junit.Tests/data/xunit-ignore.trx
Labels: MsTest, NUnit, enhancement, xunit

#48 React to deprecation of <licenseUrl>
  Directory.Build.props
  LICENSE
  source/trx2junit/trx2junit.csproj
Labels: nuget

#49 Multi-targeting for .NET Core 3.0
  .circleci/config.yml
  samples/Directory.Build.props
  source/trx2junit/trx2junit.csproj
  tests/Directory.Build.props
  tests/trx2junit.Tests/trx2junit.Tests.csproj
Labels: nuget

#50 Updated CI
  .circleci/config.yml
  .gitignore
  tests/scripts/run-different-output-location.sh
  tests/scripts/run-globbing.sh
  tests/scripts/run-multiple-args.sh
  tests/scripts/run-samples.sh
  tests/scripts/run-single-arg.sh
  trx2junit.sln
Labels: continuous-integration

#51 Check the number of converted files in globbing-test
  tests/scripts/run-globbing.sh
Labels: continuous-integration
